"""Job 6: Analytics & Daily Reporting
Schedule: Daily at 23:59 UTC
"""
from datetime import datetime, date, timedelta
from pathlib import Path
import pandas as pd
from database.models import SessionLocal, Order, Listing, Niche
from utils.notify import email_html
from config import REPORTS_DIR, get_logger

logger = get_logger("job6_analytics")

REPORT_TEMPLATE = """
<html><body style="font-family:Arial,sans-serif;max-width:800px;margin:auto">
<h1 style="color:#333">autoPOD Daily Report — {date}</h1>
<h2>Summary</h2>
<table border="1" cellpadding="8" style="border-collapse:collapse;width:100%">
  <tr><td><b>Revenue</b></td><td>${revenue:.2f}</td></tr>
  <tr><td><b>Profit</b></td><td>${profit:.2f}</td></tr>
  <tr><td><b>Margin</b></td><td>{margin:.1f}%</td></tr>
  <tr><td><b>Orders</b></td><td>{orders}</td></tr>
  <tr><td><b>Active Listings</b></td><td>{active_listings}</td></tr>
</table>
<h2>Top 10 Listings by Revenue</h2>
{top_listings_html}
<h2>Platform Breakdown</h2>
{platform_html}
<p style="color:#999;font-size:12px">Generated by autoPOD at {timestamp}</p>
</body></html>
"""


def build_daily_report(session, report_date: date) -> dict:
    start = datetime.combine(report_date, datetime.min.time())
    end = datetime.combine(report_date, datetime.max.time())

    orders_today = session.query(Order).filter(
        Order.order_date >= start, Order.order_date <= end
    ).all()

    revenue = sum(o.revenue for o in orders_today)
    profit = sum(o.profit for o in orders_today)
    margin = (profit / revenue * 100) if revenue > 0 else 0
    active_listings = session.query(Listing).filter_by(status="active").count()

    # Top listings
    listing_revenue: dict = {}
    for order in orders_today:
        lid = order.listing_id
        if lid:
            listing_revenue[lid] = listing_revenue.get(lid, 0) + order.revenue

    top_10 = sorted(listing_revenue.items(), key=lambda x: x[1], reverse=True)[:10]
    top_listings = []
    for lid, rev in top_10:
        l = session.query(Listing).get(lid)
        top_listings.append({
            "title": l.title[:60] if l else "Unknown",
            "platform": l.platform if l else "-",
            "revenue": rev,
        })

    # Platform breakdown
    platform_rev: dict = {}
    for order in orders_today:
        p = order.platform or "unknown"
        platform_rev[p] = platform_rev.get(p, 0) + order.revenue

    return {
        "date": report_date.isoformat(),
        "revenue": revenue,
        "profit": profit,
        "margin": margin,
        "orders": len(orders_today),
        "active_listings": active_listings,
        "top_listings": top_listings,
        "platform_breakdown": platform_rev,
    }


def save_markdown_report(data: dict):
    md_path = REPORTS_DIR / f"{data['date']}.md"
    lines = [
        f"# autoPOD Report — {data['date']}",
        "",
        "## Summary",
        f"- Revenue: ${data['revenue']:.2f}",
        f"- Profit: ${data['profit']:.2f}",
        f"- Margin: {data['margin']:.1f}%",
        f"- Orders: {data['orders']}",
        f"- Active Listings: {data['active_listings']}",
        "",
        "## Top Listings",
    ]
    for item in data["top_listings"]:
        lines.append(f"- {item['title']} ({item['platform']}) — ${item['revenue']:.2f}")
    lines += [
        "",
        "## Platform Breakdown",
    ]
    for platform, rev in data["platform_breakdown"].items():
        lines.append(f"- {platform}: ${rev:.2f}")

    md_path.write_text("\n".join(lines))
    logger.info(f"Report saved: {md_path}")
    return md_path


def send_html_report(data: dict):
    top_listings_rows = "".join(
        f"<tr><td>{item['title']}</td><td>{item['platform']}</td><td>${item['revenue']:.2f}</td></tr>"
        for item in data["top_listings"]
    )
    top_listings_html = f'<table border="1" cellpadding="6" style="border-collapse:collapse;width:100%"><tr><th>Title</th><th>Platform</th><th>Revenue</th></tr>{top_listings_rows}</table>'

    platform_rows = "".join(
        f"<tr><td>{p}</td><td>${r:.2f}</td></tr>"
        for p, r in data["platform_breakdown"].items()
    )
    platform_html = f'<table border="1" cellpadding="6" style="border-collapse:collapse;width:100%"><tr><th>Platform</th><th>Revenue</th></tr>{platform_rows}</table>'

    html = REPORT_TEMPLATE.format(
        **data,
        top_listings_html=top_listings_html,
        platform_html=platform_html,
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )
    email_html(f"autoPOD Daily Report — {data['date']}", html)


def run():
    logger.info("=== Job 6: Analytics started ===")
    session = SessionLocal()
    try:
        today = date.today()
        data = build_daily_report(session, today)
        save_markdown_report(data)
        send_html_report(data)
        logger.info(f"Report: revenue=${data['revenue']:.2f} profit=${data['profit']:.2f} orders={data['orders']}")
        logger.info("=== Job 6 complete ===")
    except Exception as e:
        logger.error(f"Job 6 failed: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    run()
